apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    run: redis
  namespace: labrickmorty  
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: redis
